FROM docker.io/library/archlinux:latest

LABEL maintainer="thorstenrie <https://github.com/thorstenrie/ts-bedrock>"

ARG UGID=667
ARG MCVER=1.20.0.01

EXPOSE 19132/udp
EXPOSE 43351/udp

RUN groupadd -g $UGID minecraft-bedrock && \
    useradd -r -m -l -u $UGID -g minecraft-bedrock minecraft-bedrock && \
    pacman -Syu --noconfirm && \
    pacman -S --noconfirm --needed unzip curl && \
    ln -fs /usr/share/zoneinfo/$(curl https://ipapi.co/timezone) /etc/localtime

USER minecraft-bedrock

WORKDIR /home/minecraft-bedrock

RUN mkdir -p server/worlds && \
    mkdir resource_packs && \
    mkdir behavior_packs && \
    mkdir config && \
    chmod 755 server && \
    curl https://minecraft.azureedge.net/bin-linux/bedrock-server-$MCVER.zip --output bedrock-server.zip

WORKDIR /home/minecraft-bedrock/server

COPY --chown=minecraft-bedrock:minecraft-bedrock start.sh .

CMD [ "./start.sh" ]
